 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/homepages", type: :request do
  
  # Homepage. As you add validations to Homepage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Homepage.create! valid_attributes
      get homepages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      homepage = Homepage.create! valid_attributes
      get homepage_url(homepage)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_homepage_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      homepage = Homepage.create! valid_attributes
      get edit_homepage_url(homepage)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Homepage" do
        expect {
          post homepages_url, params: { homepage: valid_attributes }
        }.to change(Homepage, :count).by(1)
      end

      it "redirects to the created homepage" do
        post homepages_url, params: { homepage: valid_attributes }
        expect(response).to redirect_to(homepage_url(Homepage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Homepage" do
        expect {
          post homepages_url, params: { homepage: invalid_attributes }
        }.to change(Homepage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post homepages_url, params: { homepage: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested homepage" do
        homepage = Homepage.create! valid_attributes
        patch homepage_url(homepage), params: { homepage: new_attributes }
        homepage.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the homepage" do
        homepage = Homepage.create! valid_attributes
        patch homepage_url(homepage), params: { homepage: new_attributes }
        homepage.reload
        expect(response).to redirect_to(homepage_url(homepage))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        homepage = Homepage.create! valid_attributes
        patch homepage_url(homepage), params: { homepage: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested homepage" do
      homepage = Homepage.create! valid_attributes
      expect {
        delete homepage_url(homepage)
      }.to change(Homepage, :count).by(-1)
    end

    it "redirects to the homepages list" do
      homepage = Homepage.create! valid_attributes
      delete homepage_url(homepage)
      expect(response).to redirect_to(homepages_url)
    end
  end
end
